apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: morty-applicationset
spec:
  generators:
  - git:
      repoURL: https://github.com/zleetch/RickMorty.git
      revision: HEAD
      directories:
      - path: kustomize/morty/overlays/*
  template:
    metadata:
      name: 'morty'
    spec:
      project: default
      source:
        repoURL: https://github.com/zleetch/RickMorty.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
  syncPolicy:
    preserveResourcesOnDeletion: true