apiVersion: v1
kind: Namespace
metadata:
  name: morty

---

apiVersion: v1
kind: Namespace
metadata:
  name: rick

---

apiVersion: v1
kind: Namespace
metadata:
  name: prometheus

---

apiVersion: v1
kind: Namespace
metadata:
  name: grafana