apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../../../helm/
helmCharts:
  - name: rick
    releaseName: rick
    includeCRDs: true
    valuesFile: values.yaml