apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../../../helm/
helmCharts:
  - name: morty
    version: 0.1.0
    releaseName: morty
    includeCRDs: true
    valuesFile: values.yaml