datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9900
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.47.0
      cacheLevel: 'High'
      disabledRecordingRules: false
      incrementalQueryOverlapWindow: 10m