apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 5.44.0
    releaseName: argocd
    namespace: argocd
    includeCRDs: true
    valuesFile: values.yaml
resources:
  - namespace.yaml