name: Morty

on:
  push:
    paths: 
      - "app/morty/**"
    branches: [ "main" ]
  pull_request:
    paths: 
      - "app/morty/**"
    branches: [ "main" ]

jobs:
  build-push:
    name: Build and Push docker image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set commit hash
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:  
          context: .
          file: ./app/morty/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/morty:${{ steps.vars.outputs.sha_short }}
      -
        name: Checkout repository
        uses: actions/checkout@v2.3.2
      -
        name: Change image tag
        run: |
          sed -E -i 's/tag: "[a-z0-9]{7}"/tag: "'${{ steps.vars.outputs.sha_short }}'"/g' ./kustomize/morty/base/values.yaml
      -
        name: Commit and push changes
        run: |
          git pull
          git config --global user.name "zleetch"
          git config --global user.email "cyber.scream99@gmail.com"

          git add ./kustomize/morty/base/values.yaml
          git commit -m "Change morty image tag"
          git push      
